version: '2'

services:
  recruitmentapp:
    image: recruitmentapp
    build:
      context: ./RecruitmentApp
      dockerfile: Dockerfile

  db:
      image: "microsoft/mssql-server-linux"
      environment:
          SA_PASSWORD: "P@ssw0rd"
          ACCEPT_EULA: "Y"